# Cache downloaded dependencies and plugins between builds.
# Not strictly necessary, but speeds up the builds.

deploy:
  only:
    - main
  image: node:20.11.1 # docker image with Node
  
  before_script:
    # The runners on the forge need a proxy to access the web. mvn
    # ignores the $http_proxy & friends variable => write a
    # configuration file that does this for us.
    - chmod 400 $CI_SSH_KEY
    # Useful only for debugging

  script:
    - cd mif10-frontend/
    - npm install
    - npm run build
    - scp -r -o StrictHostKeyChecking=no -i $CI_SSH_KEY ./dist/ gitlabci@192.168.75.63:/usr/share/nginx/html
    - cd ../mif10-backend
    - npm install
    - npm run build
    - scp -r -o StrictHostKeyChecking=no -i $CI_SSH_KEY ./dist/ gitlabci@192.168.75.63:~/backend
    - ssh -o StrictHostKeyChecking=no -i $CI_SSH_KEY gitlabci@192.168.75.63 killall -q node
    - ssh -o StrictHostKeyChecking=no -i $CI_SSH_KEY gitlabci@192.168.75.63 node backend/main.js


